"""Compile project defaults into the Laravel runtime guard's configuration."""
import json
from pathlib import Path
import yaml


def generate(cfg):
    source = Path(cfg.get('defaults', 'config/defaults.yaml'))
    values = yaml.safe_load(source.read_text()) if source.exists() else {}
    if not isinstance(values,dict): raise ValueError('defaults must be a mapping')
    blocked = []
    for qid, question in cfg.get('open_questions', {}).items():
        key = question.get('config_key')
        if question.get('kind') != 'blocker' or question.get('answered') or not key: continue
        current = values
        try:
            for part in key.split('.'): current = current[part]
        except (KeyError, TypeError): raise ValueError(f'{qid} config_key {key} is absent from defaults')
        blocked.append(key)
    def php_json(value):
        body = json.dumps(value,ensure_ascii=False).replace('\\', '\\\\').replace("'", "\\'")
        return "json_decode('" + body + "', true, 512, JSON_THROW_ON_ERROR)"
    body = '<?php\n// Generated by srashta defaults. Edit the YAML source and regenerate.\nreturn [\n'
    body += "    'values' => " + php_json(values) + ",\n    'blocked_keys' => " + php_json(sorted(blocked)) + ',\n];\n'
    path=Path('config/srashta.php');path.parent.mkdir(parents=True,exist_ok=True);path.write_text(body)
    print(f'  {path}: {len(blocked)} unresolved configuration blockers guarded')
    return 0
