#!/usr/bin/env python3
"""Step 6b - generate state-machine tests from a transition table.

A table plus "any transition not listed is forbidden" is a COMPLETE oracle:
  - transition tour : every listed transition is accepted
  - sneak path      : every unlisted (from, to) pair is rejected BY THE ACTION
Hand-writing these wastes effort and misses cases. Regenerate when the table changes.

Input: machines.yaml
  account:
    states: [active, suspended, deletion_requested, anonymised]
    terminal: [anonymised]
    transitions:
      - {from: active, to: suspended, trigger: "administrator suspends with a reason"}
"""
import sys, yaml, os, re, json

TEMPLATES = {
'pest': '''<?php
// GENERATED by pipeline/gen_transition_tests.py from machines.yaml - do not edit.
// Regenerate when the transition table changes.

use App\\Support\\StateMachines\\{Machine};

dataset('{name}_permitted', [
{permitted}
]);

dataset('{name}_forbidden', [
{forbidden}
]);

it('accepts every permitted {name} transition', function (string $from, string $to) {{
    expect({Machine}::allows($from, $to))->toBeTrue();
    {Machine}::apply($from, $to);
}})->with('{name}_permitted');

it('rejects every forbidden {name} transition at the action layer', function (string $from, string $to) {{
    expect(fn () => {Machine}::apply($from, $to))
        ->toThrow(\\App\\Support\\StateMachines\\ForbiddenTransition::class);
}})->with('{name}_forbidden');
''',
'pytest': '''# GENERATED by pipeline/gen_transition_tests.py from machines.yaml - do not edit.
import pytest
from app.state_machines import {Machine}, ForbiddenTransition

PERMITTED = [
{permitted}
]
FORBIDDEN = [
{forbidden}
]

@pytest.mark.parametrize("frm,to", PERMITTED)
def test_permitted_{name}(frm, to):
    assert {Machine}.allows(frm, to)
    {Machine}.apply(frm, to)

@pytest.mark.parametrize("frm,to", FORBIDDEN)
def test_forbidden_{name}(frm, to):
    with pytest.raises(ForbiddenTransition):
        {Machine}.apply(frm, to)
''',
'vitest': '''// GENERATED by pipeline/gen_transition_tests.py from machines.yaml - do not edit.
import {{ describe, it, expect }} from 'vitest';
import {{ {Machine}, ForbiddenTransition }} from '../src/stateMachines';

const permitted: [string, string][] = [
{permitted}
];
const forbidden: [string, string][] = [
{forbidden}
];

describe('{name} transitions', () => {{
  it.each(permitted)('accepts %s -> %s', (from, to) => {{
    expect({Machine}.allows(from, to)).toBe(true);
    {Machine}.apply(from, to);
  }});
  it.each(forbidden)('rejects %s -> %s', (from, to) => {{
    expect(() => {Machine}.apply(from, to)).toThrow(ForbiddenTransition);
  }});
}});
''',
}
FMT = {'pest': '    ["{a}", "{b}"],', 'pytest': '    ("{a}", "{b}"),', 'vitest': "  ['{a}', '{b}'],"}

def generate(machines, flavour='pest', outdir='tests/Generated'):
    os.makedirs(outdir, exist_ok=True)
    written, counts = [], {}
    for name, m in machines.items():
        if not re.fullmatch(r'[a-z][a-z0-9_]*', name):
            raise ValueError('machine name must be a lowercase identifier')
        if not all(isinstance(x, str) and x for x in m['states']):
            raise ValueError('states must be nonempty strings')
        states = list(m['states'])
        listed = {(t['from'], t['to']) for t in m['transitions']}
        terminal = set(m.get('terminal', []))
        forbidden = [(a, b) for a in states for b in states
                     if (a, b) not in listed]
        # a terminal state must have no exit at all, including to itself
        if len(states) != len(set(states)) or not states:
            raise SystemExit(f'ERROR: {name}: states must be nonempty and unique')
        if not terminal <= set(states) or any(a not in states or b not in states for a, b in listed):
            raise SystemExit(f'ERROR: {name}: unknown state in transitions or terminal set')
        if any(a in terminal for a, b in listed):
            raise SystemExit(f'ERROR: {name}: terminal state has an outgoing transition')
        def row(a, b):
            quoted = [json.dumps(x, ensure_ascii=False) for x in (a,b)]
            if flavour == 'pest': quoted = [x.replace('$', r'\$') for x in quoted]
            braces = ('(', ')') if flavour == 'pytest' else ('[', ']')
            return '    ' + braces[0] + ', '.join(quoted) + braces[1] + ','
        body = TEMPLATES[flavour].format(
            name=name, Machine=''.join(p.capitalize() for p in name.split('_')) + 'Machine',
            permitted='\n'.join(row(a,b) for a, b in sorted(listed)),
            forbidden='\n'.join(row(a,b) for a, b in sorted(forbidden)))
        ext = {'pest': 'Test.php', 'pytest': '_test.py', 'vitest': '.test.ts'}[flavour]
        fn = os.path.join(outdir, f"{name}{ext}")
        open(fn, 'w').write(body); written.append(fn)
        counts[name] = (len(listed), len(forbidden))
    return written, counts

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'machines.yaml'
    flav = sys.argv[2] if len(sys.argv) > 2 else 'pest'
    outd = sys.argv[3] if len(sys.argv) > 3 else 'tests/Generated'
    w, c = generate(yaml.safe_load(open(src)), flav, outd)
    tp = sum(v[0] for v in c.values()); tf = sum(v[1] for v in c.values())
    for n, (p, f) in c.items(): print(f"  {n:24s} {p:3d} permitted  {f:4d} sneak-path")
    print(f"generated {len(w)} file(s), {tp + tf} tests ({tp} permitted, {tf} forbidden)")
